### ISSUE TITLE
dongchedi error

### ISSUE THREAD

**Issue by vicwer** [jelly54/crawler#6]
```python
Traceback (most recent call last):
  File "parser.py", line 223, in <module>
    generate_series_txt()
  File "parser.py", line 168, in generate_series_txt
    car_se = request_car_series(data[1])
  File "parser.py", line 32, in request_car_series
    rep_json = json.loads(rep.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jelly54** [comment]
期望能提出更多有效信息
